// Re-export OpenAPI type aliases
export type {
  OpenAPIDocument,
  PathsObject,
  PathItemObject,
  OperationObject,
  SchemaObject,
  SchemaObjectWithNullable,
  ReferenceObject,
  ParameterObject,
  HeaderObject,
  RequestBodyObject,
  ResponseObject,
  ComponentsObject,
  SecuritySchemeObject,
  ServerObject,
  InfoObject,
  ContactObject,
  LicenseObject,
  TagObject,
  ArraySchemaObject,
  NonArraySchemaObject,
  BaseSchemaObject,
  ArraySchemaObjectType,
  NonArraySchemaObjectType,
} from "./openapi-types";

// Re-export guard functions
export {
  isReferenceObject,
  isArraySchemaObject,
  isNonArraySchemaObject,
  isObjectSchemaObject,
  isEnumSchema,
  isCompositionSchema,
  isMapSchema,
  isPrimitiveSchema,
} from "./guards";

// Re-export IR types
export type {
  IRExtensions,
  IRExtensionValue,
  IRAllOfModel,
  IRAnyOfModel,
  IRArrayModel,
  IRDiscriminator,
  IREndpoint,
  IREnumModel,
  IREnumValue,
  IRHttpMethod,
  IRMapModel,
  IRMetadata,
  IRModel,
  IROAuth2SecurityScheme,
  IROAuthFlow,
  IROAuthFlows,
  IRParameter,
  IRParameterInType,
  IRParameterModel,
  IRParameterProperty,
  IRProperty,
  IRRef,
  IRRequestBody,
  IRRequestBodyModel,
  IRRequestContent,
  IRResponse,
  IRResponseContent,
  IRResponseHeader,
  IRResponseModel,
  IRScalarType,
  IRSecurityRequirement,
  IRSecurityScheme,
  IRServer,
  IRServerVariable,
  IRTag,
  IRType,
  IRUnionModel,
  IRValidation,
  MimeType,
  XcgenIR,
} from "./ir";
