/**
 * TypeScript type definitions
 * Generated from: ReadOnly/WriteOnly Test API 1.0.0
 * DO NOT EDIT - This file is auto-generated
 */

/**
 * User model with readOnly fields
 */
export interface User {
  /** User ID (generated by server) */ readonly id: string;
  /** Username */ username: string;
  /** Email address */ email: string;
  /** Account creation timestamp */ readonly createdAt?: string | undefined;
  /** Last update timestamp */ readonly updatedAt?: string | undefined;
}

/**
 * User creation model with writeOnly fields
 */
export interface UserCreate {
  /** Username */ username: string;
  /** Email address */ email: string;
  /** Password (not returned in responses) */ password: string;
  /** Password confirmation */ confirmPassword: string;
}

/**
 * User update model with both readOnly and writeOnly fields
 */
export interface UserUpdate {
  /** Username */ username?: string | undefined;
  /** Email address */ email?: string | undefined;
  /** Current password for verification */ currentPassword?: string | undefined;
  /** New password */ newPassword?: string | undefined;
  /** Last login timestamp (server-managed) */ readonly lastLoginAt?: string | undefined;
}

/**
 * Parameters for GET /users/{userId}
 */
export interface GetUsersUserIdParams {
  path: {
    userId: string;
  };
}

/**
 * Parameters for PATCH /users/{userId}
 */
export interface PatchUsersUserIdParams {
  path: {
    userId: string;
  };
}
