/**
 * User model
 * Auto-generated from OpenAPI specification
 */

/**
 * User model with readOnly fields
 */
export interface User {
  /** User ID (generated by server) */ readonly id: string;
  /** Username */ username: string;
  /** Email address */ email: string;
  /** Account creation timestamp */ readonly createdAt?: Date | undefined;
  /** Last update timestamp */ readonly updatedAt?: Date | undefined;
}
