name: Release Canary

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Publish canary to npm
        run: pnpm lerna publish --canary --preid rc --dist-tag rc --yes --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
