name: Release

on:
  push:
    tags:
      - '@*/*@*'  # @openapi-xcgen/core@1.0.0 など

permissions:
  contents: write
  id-token: write

env:
  TAG_VERSION: ""

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TAG_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Publish to npm
        run: pnpm lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        run: gh release create "${{ env.TAG_VERSION }}" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
